# ~/plugins.yaml
# Plugin related actions

name: 'Plugins'
on:
  # This allows maintainers to run it manually too
  workflow_dispatch:
  # This makes the script run at the end of every day
  schedule:
    - cron: '0 0 * * *'
jobs:
  update_plugin_list:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Update plugin list
        run: node scripts/update.mjs
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am 'chore: update plugin list'
          git push
